### ISSUE TITLE
DropdownInput, as shared component

### ISSUE THREAD

**Issue by hannesqvarnstrom** [chas-academy/u10-business-idea-grupp-6#39]
Create DropdownInput in /shared/components for use in the entire project

**Comment by hannesqvarnstrom** [comment]
Use <a href="https://react-select.com/home#async">this</a>as a template

**Comment by reelode** [comment]
https://react-select.com/home#async

**Comment by reelode** [comment]
> Use [this](https://react-select.com/home#async) as a template

To small link for us to find
