### ISSUE TITLE
basic design sketch (eg landing page, registration, matching)

### ISSUE THREAD

**Issue by stenwall** [chas-academy/u10-business-idea-grupp-6#9]

**Comment by MDAX1** [comment]
Still in dev, håller på testa lite ideer. https://www.figma.com/file/cDk6QFSICtkKwoOknNX1XS/U10-wireframing-prototype?node-id=0%3A1

**Comment by MDAX1** [comment]
Progress: ![prototype](https://user-images.githubusercontent.com/55977791/117343239-60647d00-aea4-11eb-890f-28d3611d17dc.png)

**Comment by EnzoBomark** [comment]
![cb0967376a26bbdd591fa7aaabd5ca59](https://user-images.githubusercontent.com/71819938/117582369-fb0dc780-b101-11eb-8e49-568e71fa88e2.png)

**Comment by EnzoBomark** [comment]
![9767cd6e13a74b5f26afde9bf9b95472](https://user-images.githubusercontent.com/71819938/117644605-f0971080-b189-11eb-8a15-8fcfe4643b50.png)
